apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: backend
          imagePullPolicy: Always
          image: acrghactions123.azurecr.io/my-ecommerce-api:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-public-service
spec:
  type: LoadBalancer # Tells Azure to buy a Public IP
  selector:
    app: node # Looks for the pods created by the deployment above
  ports:
    - protocol: TCP
      port: 80 # The port exposed to the public internet
      targetPort: 3000 # The port your Node.js app is listening on inside the container
